"use client";

import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import {
  CustomDialog,
  CustomDialogContent,
  CustomDialogDescription,
  CustomDialogFooter,
  CustomDialogHeader,
  CustomDialogTitle,
  CustomDialogClose,
} from "@/components/customComponents/CustomDialog";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import {
  X,
  Edit,
  Mail,
  MessageSquare,
  Tag,
  UserPlus,
  TrendingUp,
  Archive,
  Trash2,
  Download,
} from "lucide-react";
import useUnifiedCustomersStore from "@/context/store/unified-customers";
import useAssignmentRulesStore from "@/context/store/assignment-rules";
import { LIFECYCLE_STAGES } from "@/types/unified-customer";
import type { CustomerLifecycleStage, Priority } from "@/types/unified-customer";
import { toast } from "sonner";

interface BulkActionsBarProps {
  selectedIds: string[];
  onClearSelection: () => void;
}

export function BulkActionsBar({ selectedIds, onClearSelection }: BulkActionsBarProps) {
  const { customers, updateCustomer } = useUnifiedCustomersStore();
  const { employees, assignCustomerManually } = useAssignmentRulesStore();
  const [showStageDialog, setShowStageDialog] = useState(false);
  const [showPriorityDialog, setShowPriorityDialog] = useState(false);
  const [showTagDialog, setShowTagDialog] = useState(false);
  const [showEmailDialog, setShowEmailDialog] = useState(false);
  const [showAssignDialog, setShowAssignDialog] = useState(false);
  const [selectedStage, setSelectedStage] = useState<CustomerLifecycleStage | "">("");
  const [selectedPriority, setSelectedPriority] = useState<Priority | "">("");
  const [newTags, setNewTags] = useState("");
  const [emailSubject, setEmailSubject] = useState("");
  const [emailBody, setEmailBody] = useState("");
  const [assignToEmployee, setAssignToEmployee] = useState("");

  const selectedCustomers = customers.filter((c) => selectedIds.includes(c.id));

  // Bulk update stage
  const handleBulkStageUpdate = () => {
    if (!selectedStage) return;

    selectedIds.forEach((id) => {
      const customer = customers.find((c) => c.id === id);
      if (customer) {
        updateCustomer(id, {
          stage: selectedStage,
          stageHistory: [
            ...customer.stageHistory,
            {
              id: `stage_${Date.now()}_${Math.random()}`,
              fromStage: customer.stage,
              toStage: selectedStage,
              changedBy: "Current User",
              changedById: "current_user_id",
              changedAt: new Date().toISOString(),
              reason: "Bulk update",
              autoGenerated: false,
            },
          ],
        });
      }
    });

    toast.success(`تم تحديث ${selectedIds.length} عميل إلى مرحلة جديدة`);
    setShowStageDialog(false);
    setSelectedStage("");
    onClearSelection();
  };

  // Bulk update priority
  const handleBulkPriorityUpdate = () => {
    if (!selectedPriority) return;

    selectedIds.forEach((id) => {
      updateCustomer(id, { priority: selectedPriority });
    });

    toast.success(`تم تحديث أولوية ${selectedIds.length} عميل`);
    setShowPriorityDialog(false);
    setSelectedPriority("");
    onClearSelection();
  };

  // Bulk add tags
  const handleBulkAddTags = () => {
    if (!newTags.trim()) return;

    const tagsArray = newTags.split(",").map((t) => t.trim()).filter(Boolean);

    selectedIds.forEach((id) => {
      const customer = customers.find((c) => c.id === id);
      if (customer) {
        const updatedTags = Array.from(new Set([...customer.tags, ...tagsArray]));
        updateCustomer(id, { tags: updatedTags });
      }
    });

    toast.success(`تم إضافة ${tagsArray.length} وسم لـ ${selectedIds.length} عميل`);
    setShowTagDialog(false);
    setNewTags("");
    onClearSelection();
  };

  // Bulk send email
  const handleBulkEmail = () => {
    // TODO: Integrate with email service
    console.log("Sending bulk email:", {
      recipients: selectedCustomers.map((c) => c.email).filter(Boolean),
      subject: emailSubject,
      body: emailBody,
    });

    toast.success(`تم إرسال البريد الإلكتروني لـ ${selectedIds.length} عميل`);
    setShowEmailDialog(false);
    setEmailSubject("");
    setEmailBody("");
    onClearSelection();
  };

  // Bulk assign
  const handleBulkAssign = async () => {
    if (!assignToEmployee) return;

    try {
      await assignCustomerManually({
        customerIds: selectedIds,
        employeeId: assignToEmployee,
        reason: "Bulk assignment",
      });

      toast.success(`تم تعيين ${selectedIds.length} عميل`);
      setShowAssignDialog(false);
      setAssignToEmployee("");
      onClearSelection();
    } catch (error) {
      toast.error("حدث خطأ أثناء التعيين");
    }
  };

  // Export selected
  const handleExport = (format: "csv" | "excel" | "pdf") => {
    // TODO: Implement actual export
    console.log(`Exporting ${selectedIds.length} customers to ${format}`);
    toast.success(`جاري تصدير ${selectedIds.length} عميل كـ ${format.toUpperCase()}`);
  };

  if (selectedIds.length === 0) return null;

  return (
    <>
      <div className="fixed bottom-6 left-1/2 -translate-x-1/2 z-50 animate-in slide-in-from-bottom-5">
        <div className="bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-full shadow-2xl px-6 py-4 flex items-center gap-4">
          {/* Selection Count */}
          <div className="flex items-center gap-2">
            <Badge variant="secondary" className="bg-white/20 text-white">
              {selectedIds.length}
            </Badge>
            <span className="font-medium">تم التحديد</span>
          </div>

          <div className="h-6 w-px bg-white/30" />

          {/* Actions */}
          <div className="flex items-center gap-2">
            {/* Change Stage */}
            <Button
              variant="ghost"
              size="sm"
              className="text-white hover:bg-white/20"
              onClick={() => setShowStageDialog(true)}
            >
              <TrendingUp className="h-4 w-4 ml-2" />
              تغيير المرحلة
            </Button>

            {/* Change Priority */}
            <Button
              variant="ghost"
              size="sm"
              className="text-white hover:bg-white/20"
              onClick={() => setShowPriorityDialog(true)}
            >
              <Edit className="h-4 w-4 ml-2" />
              الأولوية
            </Button>

            {/* Add Tags */}
            <Button
              variant="ghost"
              size="sm"
              className="text-white hover:bg-white/20"
              onClick={() => setShowTagDialog(true)}
            >
              <Tag className="h-4 w-4 ml-2" />
              إضافة وسم
            </Button>

            {/* Assign */}
            <Button
              variant="ghost"
              size="sm"
              className="text-white hover:bg-white/20"
              onClick={() => setShowAssignDialog(true)}
            >
              <UserPlus className="h-4 w-4 ml-2" />
              تعيين
            </Button>

            {/* More Actions */}
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button
                  variant="ghost"
                  size="sm"
                  className="text-white hover:bg-white/20"
                >
                  المزيد
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end" className="w-48">
                <DropdownMenuLabel>إجراءات إضافية</DropdownMenuLabel>
                <DropdownMenuSeparator />
                
                <DropdownMenuItem onClick={() => setShowEmailDialog(true)}>
                  <Mail className="h-4 w-4 ml-2" />
                  إرسال بريد
                </DropdownMenuItem>

                <DropdownMenuItem>
                  <MessageSquare className="h-4 w-4 ml-2" />
                  إرسال واتساب
                </DropdownMenuItem>

                <DropdownMenuSeparator />

                <DropdownMenuItem onClick={() => handleExport("csv")}>
                  <Download className="h-4 w-4 ml-2" />
                  تصدير CSV
                </DropdownMenuItem>

                <DropdownMenuItem onClick={() => handleExport("excel")}>
                  <Download className="h-4 w-4 ml-2" />
                  تصدير Excel
                </DropdownMenuItem>

                <DropdownMenuItem onClick={() => handleExport("pdf")}>
                  <Download className="h-4 w-4 ml-2" />
                  تصدير PDF
                </DropdownMenuItem>

                <DropdownMenuSeparator />

                <DropdownMenuItem className="text-red-600">
                  <Archive className="h-4 w-4 ml-2" />
                  أرشفة
                </DropdownMenuItem>

                <DropdownMenuItem className="text-red-600">
                  <Trash2 className="h-4 w-4 ml-2" />
                  حذف
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>

          <div className="h-6 w-px bg-white/30" />

          {/* Clear Selection */}
          <Button
            variant="ghost"
            size="sm"
            className="text-white hover:bg-white/20"
            onClick={onClearSelection}
          >
            <X className="h-4 w-4" />
          </Button>
        </div>
      </div>

      {/* Change Stage Dialog */}
      <CustomDialog open={showStageDialog} onOpenChange={setShowStageDialog}>
        <CustomDialogContent className="dir-rtl">
          <CustomDialogClose onClose={() => setShowStageDialog(false)} />
          <CustomDialogHeader>
            <CustomDialogTitle>تغيير المرحلة - {selectedIds.length} عميل</CustomDialogTitle>
            <CustomDialogDescription>
              اختر المرحلة الجديدة للعملاء المحددين
            </CustomDialogDescription>
          </CustomDialogHeader>

          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label>المرحلة الجديدة</Label>
              <Select
                value={selectedStage}
                onValueChange={(value) => setSelectedStage(value as CustomerLifecycleStage)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="اختر المرحلة" />
                </SelectTrigger>
                <SelectContent>
                  {LIFECYCLE_STAGES.map((stage) => (
                    <SelectItem key={stage.id} value={stage.id}>
                      <div className="flex items-center gap-2">
                        <div
                          className="w-3 h-3 rounded-full"
                          style={{ backgroundColor: stage.color }}
                        />
                        {stage.nameAr}
                      </div>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <CustomDialogFooter>
            <Button variant="outline" onClick={() => setShowStageDialog(false)}>
              إلغاء
            </Button>
            <Button onClick={handleBulkStageUpdate} disabled={!selectedStage}>
              تحديث المرحلة
            </Button>
          </CustomDialogFooter>
        </CustomDialogContent>
      </CustomDialog>

      {/* Change Priority Dialog */}
      <CustomDialog open={showPriorityDialog} onOpenChange={setShowPriorityDialog}>
        <CustomDialogContent className="dir-rtl">
          <CustomDialogClose onClose={() => setShowPriorityDialog(false)} />
          <CustomDialogHeader>
            <CustomDialogTitle>تغيير الأولوية - {selectedIds.length} عميل</CustomDialogTitle>
            <CustomDialogDescription>
              اختر الأولوية الجديدة للعملاء المحددين
            </CustomDialogDescription>
          </CustomDialogHeader>

          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label>الأولوية الجديدة</Label>
              <Select
                value={selectedPriority}
                onValueChange={(value) => setSelectedPriority(value as Priority)}
              >
                <SelectTrigger>
                  <SelectValue placeholder="اختر الأولوية" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="urgent">🚨 عاجل</SelectItem>
                  <SelectItem value="high">🔥 عالي</SelectItem>
                  <SelectItem value="medium">⭐ متوسط</SelectItem>
                  <SelectItem value="low">📌 منخفض</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <CustomDialogFooter>
            <Button variant="outline" onClick={() => setShowPriorityDialog(false)}>
              إلغاء
            </Button>
            <Button onClick={handleBulkPriorityUpdate} disabled={!selectedPriority}>
              تحديث الأولوية
            </Button>
          </CustomDialogFooter>
        </CustomDialogContent>
      </CustomDialog>

      {/* Add Tags Dialog */}
      <CustomDialog open={showTagDialog} onOpenChange={setShowTagDialog}>
        <CustomDialogContent className="dir-rtl">
          <CustomDialogClose onClose={() => setShowTagDialog(false)} />
          <CustomDialogHeader>
            <CustomDialogTitle>إضافة وسوم - {selectedIds.length} عميل</CustomDialogTitle>
            <CustomDialogDescription>
              أدخل الوسوم مفصولة بفواصل
            </CustomDialogDescription>
          </CustomDialogHeader>

          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label>الوسوم</Label>
              <Textarea
                placeholder="مثال: عميل مهم، متابعة سريعة، مستثمر"
                value={newTags}
                onChange={(e) => setNewTags(e.target.value)}
                rows={3}
              />
            </div>
          </div>

          <CustomDialogFooter>
            <Button variant="outline" onClick={() => setShowTagDialog(false)}>
              إلغاء
            </Button>
            <Button onClick={handleBulkAddTags} disabled={!newTags.trim()}>
              إضافة الوسوم
            </Button>
          </CustomDialogFooter>
        </CustomDialogContent>
      </CustomDialog>

      {/* Send Email Dialog */}
      <CustomDialog open={showEmailDialog} onOpenChange={setShowEmailDialog} maxWidth="max-w-2xl">
        <CustomDialogContent className="dir-rtl">
          <CustomDialogClose onClose={() => setShowEmailDialog(false)} />
          <CustomDialogHeader>
            <CustomDialogTitle>إرسال بريد إلكتروني - {selectedIds.length} عميل</CustomDialogTitle>
            <CustomDialogDescription>
              سيتم إرسال البريد لكل العملاء المحددين
            </CustomDialogDescription>
          </CustomDialogHeader>

          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label>الموضوع</Label>
              <input
                type="text"
                className="w-full px-3 py-2 border rounded-md"
                placeholder="موضوع البريد الإلكتروني"
                value={emailSubject}
                onChange={(e) => setEmailSubject(e.target.value)}
              />
            </div>

            <div className="space-y-2">
              <Label>الرسالة</Label>
              <Textarea
                placeholder="نص الرسالة..."
                value={emailBody}
                onChange={(e) => setEmailBody(e.target.value)}
                rows={8}
              />
            </div>

            <div className="text-sm text-gray-500">
              يمكنك استخدام المتغيرات: {"{customerName}"}, {"{propertyName}"}, {"{agentName}"}
            </div>
          </div>

          <CustomDialogFooter>
            <Button variant="outline" onClick={() => setShowEmailDialog(false)}>
              إلغاء
            </Button>
            <Button onClick={handleBulkEmail} disabled={!emailSubject || !emailBody}>
              <Mail className="h-4 w-4 ml-2" />
              إرسال البريد
            </Button>
          </CustomDialogFooter>
        </CustomDialogContent>
      </CustomDialog>

      {/* Assign Dialog */}
      <CustomDialog open={showAssignDialog} onOpenChange={setShowAssignDialog}>
        <CustomDialogContent className="dir-rtl">
          <CustomDialogClose onClose={() => setShowAssignDialog(false)} />
          <CustomDialogHeader>
            <CustomDialogTitle>تعيين موظف - {selectedIds.length} عميل</CustomDialogTitle>
            <CustomDialogDescription>
              اختر الموظف المسؤول عن العملاء المحددين
            </CustomDialogDescription>
          </CustomDialogHeader>

          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label>الموظف</Label>
              <Select value={assignToEmployee} onValueChange={setAssignToEmployee}>
                <SelectTrigger>
                  <SelectValue placeholder="اختر الموظف" />
                </SelectTrigger>
                <SelectContent>
                  {employees.filter((e) => e.isActive).map((employee) => (
                    <SelectItem key={employee.id} value={employee.id}>
                      <div className="flex items-center gap-2">
                        <span>{employee.name}</span>
                        <span className="text-xs text-gray-500">
                          ({employee.loadPercentage}% تحميل)
                        </span>
                      </div>
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          </div>

          <CustomDialogFooter>
            <Button variant="outline" onClick={() => setShowAssignDialog(false)}>
              إلغاء
            </Button>
            <Button onClick={handleBulkAssign} disabled={!assignToEmployee}>
              تعيين الموظف
            </Button>
          </CustomDialogFooter>
        </CustomDialogContent>
      </CustomDialog>
    </>
  );
}
