// Unified Customer Types for Real Estate Customer Hub
// Designed for Saudi Arabia and Gulf Region Real Estate Operations

export type CustomerSource = 
  | 'inquiry'      // From website inquiry form
  | 'manual'       // Manually added by agent
  | 'whatsapp'     // From WhatsApp conversation
  | 'import'       // Bulk import
  | 'referral';    // Customer referral

export type CustomerActionType = 
  | 'new_inquiry'        // New customer interested in property
  | 'callback_request'   // Customer requested callback
  | 'property_match'     // New property matches customer preferences
  | 'follow_up'          // Scheduled follow-up
  | 'document_required'  // Documents pending
  | 'payment_due'        // Payment reminder
  | 'site_visit'         // Site visit to schedule/confirm
  | 'whatsapp_incoming'  // New WhatsApp message
  | 'ai_recommended';    // AI-generated recommendation

export type CustomerActionStatus = 'pending' | 'in_progress' | 'completed' | 'dismissed' | 'snoozed';

export interface CustomerAction {
  id: string;
  customerId: string;
  customerName: string;
  type: CustomerActionType;
  title: string;
  description?: string;
  priority: Priority;
  status: CustomerActionStatus;
  source: CustomerSource;
  dueDate?: string;
  snoozedUntil?: string;
  assignedTo?: string;
  assignedToName?: string;
  createdAt: string;
  completedAt?: string;
  completedBy?: string;
  metadata?: Record<string, any>;
}

export type CustomerLifecycleStage =
  | 'new_lead'           // عميل جديد
  | 'qualified'          // مؤهل
  | 'property_matching'  // مطابقة العقارات
  | 'site_visit'         // معاينة
  | 'negotiation'        // تفاوض
  | 'contract_prep'      // إعداد العقد
  | 'down_payment'       // الدفعة الأولى
  | 'closing'            // إتمام الصفقة
  | 'post_sale';         // ما بعد البيع

export type PropertyPurpose = 'buy' | 'rent' | 'invest';
export type Timeline = 'immediate' | '1-3months' | '3-6months' | '6months+';
export type ChurnRisk = 'low' | 'medium' | 'high';
export type Priority = 'low' | 'medium' | 'high' | 'urgent';

export interface LifecycleStageInfo {
  id: CustomerLifecycleStage;
  nameAr: string;
  nameEn: string;
  description: string;
  color: string;
  icon: string;
  order: number;
}

export interface SourceDetails {
  inquiryId?: string;
  referredBy?: string;
  referrerName?: string;
  campaign?: string;
  landingPage?: string;
  utmSource?: string;
  notes?: string;
}

export interface CustomerPreferences {
  propertyType: string[];  // ['villa', 'apartment', 'land', 'commercial']
  budgetMin?: number;
  budgetMax?: number;
  preferredAreas: string[];  // City - District format
  preferredCities?: string[];
  bedrooms?: number;
  bathrooms?: number;
  minArea?: number;  // in square meters
  maxArea?: number;
  purpose: PropertyPurpose;
  timeline: Timeline;
  amenities?: string[];  // ['pool', 'garage', 'garden', etc.]
  floorPreference?: string;  // 'ground', 'middle', 'top'
  furnishing?: 'furnished' | 'unfurnished' | 'semi-furnished' | 'any';
  notes?: string;
}

export interface AIInsights {
  nextBestAction?: string;
  nextBestActionEn?: string;
  churnRisk?: ChurnRisk;
  churnReasons?: string[];
  propertyMatches?: string[];  // Property IDs
  predictedCloseDate?: string;
  recommendedFollowUpDate?: string;
  sentimentScore?: number;  // -100 to 100
  engagementLevel?: 'very_low' | 'low' | 'medium' | 'high' | 'very_high';
  conversionProbability?: number;  // 0-100
  aiNotes?: string;
}

export interface StageChange {
  id: string;
  fromStage: CustomerLifecycleStage | null;
  toStage: CustomerLifecycleStage;
  changedBy: string;  // Employee name
  changedById: string;  // Employee ID
  changedAt: string;
  reason?: string;
  notes?: string;
  autoGenerated: boolean;
}

export interface PropertyInterest {
  id: string;
  propertyId: string;
  propertyTitle: string;
  propertyTitleEn?: string;
  propertyImage?: string;
  propertyPrice?: number;
  propertyType?: string;
  propertyLocation?: string;
  status: 'interested' | 'viewing_scheduled' | 'viewed' | 'liked' | 'rejected' | 'offer_made';
  addedAt: string;
  viewedAt?: string;
  feedback?: string;
  rating?: number;  // 1-5
  notes?: string;
}

export interface Interaction {
  id: string;
  type: 'call' | 'whatsapp' | 'email' | 'meeting' | 'site_visit' | 'note' | 'sms';
  direction?: 'inbound' | 'outbound';
  date: string;
  duration?: number;  // in minutes
  notes: string;
  outcome?: string;
  agentName: string;
  agentId: string;
  sentiment?: 'positive' | 'neutral' | 'negative';
  followUpRequired?: boolean;
  followUpDate?: string;
}

export interface Appointment {
  id: string;
  title: string;
  titleEn?: string;
  type: 'site_visit' | 'office_meeting' | 'phone_call' | 'video_call' | 'contract_signing' | 'other';
  date: string;
  time: string;
  datetime?: string;
  duration: number;  // in minutes
  location?: string;
  propertyId?: string;
  propertyTitle?: string;
  status: 'scheduled' | 'confirmed' | 'completed' | 'cancelled' | 'no_show';
  priority: Priority;
  notes?: string;
  agentName?: string;
  agentId?: string;
  reminderSent?: boolean;
  outcome?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Reminder {
  id: string;
  title: string;
  titleEn?: string;
  description?: string;
  datetime: string;
  priority: Priority;
  status: 'pending' | 'completed' | 'overdue' | 'cancelled';
  type: 'follow_up' | 'document' | 'payment' | 'viewing' | 'general';
  relatedTo?: string;  // appointment ID, property ID, etc.
  createdBy: string;
  createdById: string;
  completedAt?: string;
  isOverdue?: boolean;
  daysUntilDue?: number;
}

export interface Document {
  id: string;
  name: string;
  type: 'id_copy' | 'contract' | 'agreement' | 'receipt' | 'photo' | 'other';
  fileUrl: string;
  fileSize?: number;
  mimeType?: string;
  uploadedBy: string;
  uploadedById: string;
  uploadedAt: string;
  description?: string;
  tags?: string[];
}

export interface Employee {
  id: string;
  name: string;
  nameEn?: string;
  email?: string;
  phone?: string;
  whatsapp?: string;
  role?: string;
  avatar?: string;
  isActive?: boolean;
}

// ============================================================================
// KSA-Specific Types for Saudi Arabia Real Estate Market
// ============================================================================

// REGA/FAL Broker Licensing & Compliance
export type BrokerageLicenseStatus = 'active' | 'expired' | 'suspended' | 'pending' | 'none';
export type BrokerageContractStatus = 'draft' | 'pending_approval' | 'active' | 'completed' | 'cancelled';

export interface BrokerageLicense {
  licenseNumber?: string;
  licenseType?: 'individual' | 'establishment';
  status: BrokerageLicenseStatus;
  issuedDate?: string;
  expiryDate?: string;
  issuedBy?: string;  // e.g., "REGA/FAL"
  verifiedAt?: string;
  notes?: string;
}

export interface BrokerageContract {
  id: string;
  contractNumber?: string;
  type: 'sale' | 'rent' | 'both';
  status: BrokerageContractStatus;
  propertyId?: string;
  propertyTitle?: string;
  commissionRate?: number;  // percentage
  commissionAmount?: number;
  exclusivityPeriod?: number;  // in days
  startDate: string;
  endDate?: string;
  approvedBy?: string;
  approvedAt?: string;
  regaContractId?: string;  // REGA platform contract ID
  documents?: string[];  // Document IDs
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

// EJAR Rental Compliance
export type EjarContractStatus = 'draft' | 'pending' | 'active' | 'expired' | 'terminated' | 'renewed';
export type TenancyType = 'residential' | 'commercial' | 'industrial';

export interface EjarContract {
  id: string;
  ejarContractNumber?: string;  // Official EJAR contract number
  propertyId?: string;
  propertyTitle?: string;
  tenancyType: TenancyType;
  status: EjarContractStatus;
  startDate: string;
  endDate: string;
  monthlyRent: number;
  securityDeposit?: number;
  paymentSchedule?: 'monthly' | 'quarterly' | 'semi-annual' | 'annual';
  landlordId?: string;
  landlordName?: string;
  tenantName?: string;
  createdInEjar?: boolean;
  ejarCreatedAt?: string;
  ejarUrl?: string;
  autoRenewal?: boolean;
  renewalNotificationSent?: boolean;
  documents?: string[];
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

// Wafi Off-Plan Developer Workflow
export type WafiProjectStatus = 'planning' | 'licensed' | 'construction' | 'completed' | 'handed_over';
export type EscrowMilestoneStatus = 'pending' | 'in_progress' | 'certified' | 'released' | 'overdue';

export interface WafiLicense {
  licenseNumber?: string;
  projectId?: string;
  projectName?: string;
  developerName?: string;
  status: WafiProjectStatus;
  issuedDate?: string;
  totalUnits?: number;
  soldUnits?: number;
  reservedUnits?: number;
  verifiedAt?: string;
  notes?: string;
}

export interface EscrowMilestone {
  id: string;
  projectId?: string;
  milestoneNumber: number;
  title: string;
  titleEn?: string;
  description?: string;
  targetDate: string;
  completionDate?: string;
  status: EscrowMilestoneStatus;
  percentage: number;  // % of total project
  amount?: number;
  certifiedBy?: string;  // Consulting office
  certifiedAt?: string;
  releaseRequested?: boolean;
  releaseApproved?: boolean;
  releaseDate?: string;
  documents?: string[];
  notes?: string;
  isOverdue?: boolean;
}

export interface HandoverDefect {
  id: string;
  unitId?: string;
  category: 'structural' | 'electrical' | 'plumbing' | 'finishing' | 'hvac' | 'other';
  severity: 'critical' | 'major' | 'minor';
  description: string;
  reportedBy?: string;
  reportedAt: string;
  status: 'open' | 'in_progress' | 'resolved' | 'deferred';
  assignedTo?: string;
  targetResolutionDate?: string;
  resolvedAt?: string;
  photos?: string[];
  notes?: string;
}

// Sakani/NHC Housing Programs
export type SakaniEligibilityStatus = 'not_checked' | 'eligible' | 'not_eligible' | 'pending_verification';
export type SakaniProductType = 'ready_unit' | 'under_construction' | 'self_construction' | 'moh_land' | 'easy_installment';

export interface SakaniEligibility {
  status: SakaniEligibilityStatus;
  sakaniId?: string;  // Beneficiary ID in Sakani system
  eligibilityCheckedAt?: string;
  interestedProducts?: SakaniProductType[];
  householdIncome?: number;
  householdSize?: number;
  firstTimeOwner?: boolean;
  currentlyOwnsProperty?: boolean;
  eligibilityNotes?: string;
  approvedLoanAmount?: number;
  downPaymentSupport?: number;
  verifiedAt?: string;
}

// Real Estate Registry
export interface RegistryInfo {
  deedNumber?: string;  // صك الملكية
  registryOffice?: string;
  registeredOwner?: string;
  registrationDate?: string;
  verifiedAt?: string;
  notes?: string;
}

// Financing & Mortgage
export type MortgageStatus = 'not_applied' | 'pre_approved' | 'application_submitted' | 'approved' | 'rejected' | 'disbursed';
export type FinancingType = 'conventional' | 'islamic' | 'subsidized' | 'self_funded';

export interface MortgageInfo {
  status: MortgageStatus;
  financingType?: FinancingType;
  bankName?: string;
  applicationNumber?: string;
  preApprovedAmount?: number;
  approvedAmount?: number;
  interestRate?: number;
  loanTenure?: number;  // in years
  monthlyPayment?: number;
  downPaymentRequired?: number;
  downPaymentPaid?: number;
  applicationDate?: string;
  approvalDate?: string;
  disbursementDate?: string;
  redfSupport?: boolean;  // Real Estate Development Fund
  redfAmount?: number;
  documents?: string[];
  notes?: string;
}

export interface PaymentSchedule {
  id: string;
  type: 'down_payment' | 'installment' | 'escrow_release' | 'final_payment' | 'other';
  description: string;
  amount: number;
  dueDate: string;
  status: 'pending' | 'paid' | 'overdue' | 'cancelled';
  paidAmount?: number;
  paidDate?: string;
  paymentMethod?: string;
  receiptNumber?: string;
  escrowAccount?: string;
  notes?: string;
}

// KSA Compliance Summary
export interface KSACompliance {
  brokerageLicense?: BrokerageLicense;
  brokerageContracts?: BrokerageContract[];
  ejarContracts?: EjarContract[];
  wafiLicense?: WafiLicense;
  escrowMilestones?: EscrowMilestone[];
  handoverDefects?: HandoverDefect[];
  sakaniEligibility?: SakaniEligibility;
  registryInfo?: RegistryInfo;
  mortgageInfo?: MortgageInfo;
  paymentSchedule?: PaymentSchedule[];
}

export interface UnifiedCustomer {
  // Core Identity
  id: string;
  name: string;
  nameEn?: string;
  phone: string;
  whatsapp?: string;
  email?: string;
  nationalId?: string;
  nationality?: string;
  gender?: 'male' | 'female';
  dateOfBirth?: string;
  
  // Source Tracking
  source: CustomerSource;
  sourceDetails?: SourceDetails;
  
  // Lifecycle
  stage: CustomerLifecycleStage;
  stageHistory: StageChange[];
  
  // Preferences (Real Estate Specific)
  preferences: CustomerPreferences;
  
  // AI-Powered Fields
  leadScore: number;  // 0-100
  aiInsights: AIInsights;
  
  // Priority & Classification
  priority: Priority;
  customerType?: string;  // 'individual', 'investor', 'company'
  tags: string[];
  
  // Relationships
  assignedEmployee?: Employee;
  assignedEmployeeId?: string;
  properties: PropertyInterest[];
  interactions: Interaction[];
  appointments: Appointment[];
  reminders: Reminder[];
  documents: Document[];
  
  // Financial
  totalDealValue?: number;
  expectedRevenue?: number;
  paidAmount?: number;
  
  // Metadata
  createdAt: string;
  updatedAt: string;
  lastContactAt?: string;
  lastContactType?: string;
  nextFollowUpDate?: string;
  
  // Additional Info
  address?: string;
  city?: string;
  district?: string;
  notes?: string;
  familySize?: number;
  occupation?: string;
  
  // Location (for map view)
  latitude?: number;
  longitude?: number;
  
  // Stats
  totalInteractions?: number;
  totalAppointments?: number;
  totalPropertyViews?: number;
  responseRate?: number;  // 0-100
  avgResponseTime?: number;  // in hours
  
  // KSA-Specific Compliance & Workflows
  ksaCompliance?: KSACompliance;
}

// Lifecycle Stage Definitions
export const LIFECYCLE_STAGES: LifecycleStageInfo[] = [
  {
    id: 'new_lead',
    nameAr: 'عميل جديد',
    nameEn: 'New Lead',
    description: 'Initial inquiry from any source',
    color: '#3b82f6',  // blue
    icon: 'UserPlus',
    order: 1,
  },
  {
    id: 'qualified',
    nameAr: 'مؤهل',
    nameEn: 'Qualified',
    description: 'Budget, timeline, and preferences confirmed',
    color: '#8b5cf6',  // purple
    icon: 'UserCheck',
    order: 2,
  },
  {
    id: 'property_matching',
    nameAr: 'مطابقة العقارات',
    nameEn: 'Property Matching',
    description: 'AI-assisted property recommendations',
    color: '#06b6d4',  // cyan
    icon: 'Search',
    order: 3,
  },
  {
    id: 'site_visit',
    nameAr: 'معاينة',
    nameEn: 'Site Visit',
    description: 'Property viewing scheduled or completed',
    color: '#10b981',  // green
    icon: 'MapPin',
    order: 4,
  },
  {
    id: 'negotiation',
    nameAr: 'تفاوض',
    nameEn: 'Negotiation',
    description: 'Price and terms discussion',
    color: '#f59e0b',  // amber
    icon: 'MessageSquare',
    order: 5,
  },
  {
    id: 'contract_prep',
    nameAr: 'إعداد العقد',
    nameEn: 'Contract Preparation',
    description: 'Legal documentation preparation',
    color: '#f97316',  // orange
    icon: 'FileText',
    order: 6,
  },
  {
    id: 'down_payment',
    nameAr: 'الدفعة الأولى',
    nameEn: 'Down Payment',
    description: 'Initial payment received',
    color: '#84cc16',  // lime
    icon: 'DollarSign',
    order: 7,
  },
  {
    id: 'closing',
    nameAr: 'إتمام الصفقة',
    nameEn: 'Closing',
    description: 'Final transaction completion',
    color: '#22c55e',  // green
    icon: 'CheckCircle',
    order: 8,
  },
  {
    id: 'post_sale',
    nameAr: 'ما بعد البيع',
    nameEn: 'Post-Sale',
    description: 'Handover, support, and referral nurturing',
    color: '#6366f1',  // indigo
    icon: 'Award',
    order: 9,
  },
];

// Helper Functions
export const getStageInfo = (stageId: CustomerLifecycleStage): LifecycleStageInfo | undefined => {
  return LIFECYCLE_STAGES.find(s => s.id === stageId);
};

export const getStageColor = (stageId: CustomerLifecycleStage): string => {
  return getStageInfo(stageId)?.color || '#6b7280';
};

export const getStageNameAr = (stageId: CustomerLifecycleStage): string => {
  return getStageInfo(stageId)?.nameAr || stageId;
};

export const getStageNameEn = (stageId: CustomerLifecycleStage): string => {
  return getStageInfo(stageId)?.nameEn || stageId;
};

export const calculateLeadScore = (customer: Partial<UnifiedCustomer>): number => {
  let score = 50; // Base score
  
  // Source quality (0-15 points)
  if (customer.source === 'referral') score += 15;
  else if (customer.source === 'inquiry') score += 10;
  else if (customer.source === 'whatsapp') score += 8;
  else if (customer.source === 'manual') score += 5;
  
  // Budget alignment (0-20 points)
  if (customer.preferences?.budgetMin && customer.preferences.budgetMin > 500000) {
    score += 20;
  } else if (customer.preferences?.budgetMin && customer.preferences.budgetMin > 200000) {
    score += 15;
  } else if (customer.preferences?.budgetMin) {
    score += 10;
  }
  
  // Timeline urgency (0-15 points)
  if (customer.preferences?.timeline === 'immediate') score += 15;
  else if (customer.preferences?.timeline === '1-3months') score += 12;
  else if (customer.preferences?.timeline === '3-6months') score += 8;
  else if (customer.preferences?.timeline === '6months+') score += 5;
  
  // Engagement (0-20 points)
  const totalInteractions = customer.totalInteractions || 0;
  if (totalInteractions >= 10) score += 20;
  else if (totalInteractions >= 5) score += 15;
  else if (totalInteractions >= 2) score += 10;
  else if (totalInteractions >= 1) score += 5;
  
  // Response rate (0-15 points)
  const responseRate = customer.responseRate || 0;
  if (responseRate >= 90) score += 15;
  else if (responseRate >= 70) score += 12;
  else if (responseRate >= 50) score += 8;
  else if (responseRate >= 30) score += 5;
  
  // Stage progression (0-15 points)
  const stageOrder = getStageInfo(customer.stage as CustomerLifecycleStage)?.order || 1;
  if (stageOrder >= 7) score += 15;
  else if (stageOrder >= 5) score += 12;
  else if (stageOrder >= 3) score += 8;
  else score += 5;
  
  return Math.min(100, Math.max(0, score));
};

// Filters and Statistics Types
export interface CustomerFilters {
  search?: string;
  stage?: CustomerLifecycleStage[];
  source?: CustomerSource[];
  priority?: Priority[];
  assignedEmployee?: string[];
  leadScoreMin?: number;
  leadScoreMax?: number;
  budgetMin?: number;
  budgetMax?: number;
  propertyType?: string[];
  preferredAreas?: string[];
  tags?: string[];
  createdFrom?: string;
  createdTo?: string;
  lastContactFrom?: string;
  lastContactTo?: string;
  
  // KSA-Specific Filters
  brokerageLicenseStatus?: BrokerageLicenseStatus[];
  brokerageContractStatus?: BrokerageContractStatus[];
  ejarContractStatus?: EjarContractStatus[];
  wafiProjectStatus?: WafiProjectStatus[];
  sakaniEligibility?: SakaniEligibilityStatus[];
  mortgageStatus?: MortgageStatus[];
  hasEscrowOverdue?: boolean;
  hasHandoverDefects?: boolean;
}

export interface CustomerStatistics {
  total: number;
  byStage: Record<CustomerLifecycleStage, number>;
  bySource: Record<CustomerSource, number>;
  byPriority: Record<Priority, number>;
  avgLeadScore: number;
  totalDealValue: number;
  conversionRate: number;
  avgDaysInPipeline: number;
  activeCustomers: number;
  newThisMonth: number;
  closedThisMonth: number;
}
