import { PageSeoData } from "../types/types";

export const DEFAULT_SEO_DATA: Record<string, PageSeoData> = {
  "/": {
    TitleAr: "الصفحة الرئيسية",
    TitleEn: "Homepage",
    DescriptionAr: "مرحباً بكم في موقعنا - الصفحة الرئيسية",
    DescriptionEn: "Welcome to our website - Homepage",
    KeywordsAr: "الرئيسية, الموقع, الصفحة الرئيسية",
    KeywordsEn: "homepage, main, website",
    Author: "الموقع",
    AuthorEn: "Website",
    Robots: "index, follow",
    RobotsEn: "index, follow",
    "og:title": "الصفحة الرئيسية",
    "og:description": "مرحباً بكم في موقعنا",
    "og:keywords": "الرئيسية, الموقع",
    "og:author": "الموقع",
    "og:robots": "index, follow",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
    "og:locale": "ar",
    "og:locale:alternate": "en",
    "og:site_name": "الموقع",
    "og:image:width": null,
    "og:image:height": null,
    "og:image:type": null,
    "og:image:alt": "الصفحة الرئيسية",
  },
  "": {
    TitleAr: "الصفحة الرئيسية",
    TitleEn: "Homepage",
    DescriptionAr: "مرحباً بكم في موقعنا - الصفحة الرئيسية",
    DescriptionEn: "Welcome to our website - Homepage",
    KeywordsAr: "الرئيسية, الموقع, الصفحة الرئيسية",
    KeywordsEn: "homepage, main, website",
    Author: "الموقع",
    AuthorEn: "Website",
    Robots: "index, follow",
    RobotsEn: "index, follow",
    "og:title": "الصفحة الرئيسية",
    "og:description": "مرحباً بكم في موقعنا",
    "og:keywords": "الرئيسية, الموقع",
    "og:author": "الموقع",
    "og:robots": "index, follow",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
    "og:locale": "ar",
    "og:locale:alternate": "en",
    "og:site_name": "الموقع",
    "og:image:width": null,
    "og:image:height": null,
    "og:image:type": null,
    "og:image:alt": "الصفحة الرئيسية",
  },
  "create-request": {
    TitleAr: "إنشاء طلب",
    TitleEn: "Create Request",
    DescriptionAr: "إنشاء طلب جديد للحصول على الخدمات",
    DescriptionEn: "Create a new request to get our services",
    KeywordsAr: "إنشاء طلب, خدمات, طلب جديد",
    KeywordsEn: "create request, services, new request",
    Author: "الموقع",
    AuthorEn: "Website",
    Robots: "index, follow",
    RobotsEn: "index, follow",
    "og:title": "إنشاء طلب",
    "og:description": "إنشاء طلب جديد للحصول على الخدمات",
    "og:keywords": "إنشاء طلب, خدمات",
    "og:author": "الموقع",
    "og:robots": "index, follow",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
    "og:locale": "ar",
    "og:locale:alternate": "en",
    "og:site_name": "الموقع",
    "og:image:width": null,
    "og:image:height": null,
    "og:image:type": null,
    "og:image:alt": "إنشاء طلب",
  },
  "for-rent": {
    TitleAr: "عقارات للإيجار",
    TitleEn: "For Rent",
    DescriptionAr: "عقارات متاحة للإيجار",
    DescriptionEn: "Properties available for rent",
    KeywordsAr: "للإيجار, عقارات, شقق, منازل",
    KeywordsEn: "for rent, properties, apartments, houses",
    Author: "الموقع",
    AuthorEn: "Website",
    Robots: "index, follow",
    RobotsEn: "index, follow",
    "og:title": "للإيجار",
    "og:description": "عقارات متاحة للإيجار",
    "og:keywords": "للإيجار, عقارات",
    "og:author": "الموقع",
    "og:robots": "index, follow",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
    "og:locale": "ar",
    "og:locale:alternate": "en",
    "og:site_name": "الموقع",
    "og:image:width": null,
    "og:image:height": null,
    "og:image:type": null,
    "og:image:alt": "للإيجار",
  },
  "for-sale": {
    TitleAr: "عقارات للبيع",
    TitleEn: "For Sale",
    DescriptionAr: "عقارات متاحة للبيع",
    DescriptionEn: "Properties available for sale",
    KeywordsAr: "للبيع, عقارات, شقق, منازل",
    KeywordsEn: "for sale, properties, apartments, houses",
    Author: "الموقع",
    AuthorEn: "Website",
    Robots: "index, follow",
    RobotsEn: "index, follow",
    "og:title": "للبيع",
    "og:description": "عقارات متاحة للبيع",
    "og:keywords": "للبيع, عقارات",
    "og:author": "الموقع",
    "og:robots": "index, follow",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
    "og:locale": "ar",
    "og:locale:alternate": "en",
    "og:site_name": "الموقع",
    "og:image:width": null,
    "og:image:height": null,
    "og:image:type": null,
    "og:image:alt": "للبيع",
  },
  "real-estate": {
    TitleAr: "العقارات والمشاريع",
    TitleEn: "Real Estate & Projects",
    DescriptionAr: "اكتشف أفضل العقارات والمشاريع الاستثمارية المتاحة في المنطقة",
    DescriptionEn: "Discover the best available properties and investment projects in the area",
    KeywordsAr: "عقارات, مشاريع, استثمار, عقار للبيع, عقار للإيجار, مشاريع عقارية",
    KeywordsEn: "real estate, projects, investment, property for sale, property for rent, real estate projects",
    Author: "الموقع",
    AuthorEn: "Website",
    Robots: "index, follow",
    RobotsEn: "index, follow",
    "og:title": "العقارات والمشاريع",
    "og:description": "اكتشف أفضل العقارات والمشاريع الاستثمارية المتاحة",
    "og:keywords": "عقارات, مشاريع, استثمار",
    "og:author": "الموقع",
    "og:robots": "index, follow",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
    "og:locale": "ar",
    "og:locale:alternate": "en",
    "og:site_name": "الموقع",
    "og:image:width": null,
    "og:image:height": null,
    "og:image:type": null,
    "og:image:alt": "العقارات والمشاريع",
  },
  projects: {
    TitleAr: "المشاريع",
    TitleEn: "Projects",
    DescriptionAr: "مشاريعنا العقارية المتميزة",
    DescriptionEn: "Our distinguished real estate projects",
    KeywordsAr: "مشاريع, عقارية, تطوير, بناء",
    KeywordsEn: "projects, real estate, development, construction",
    Author: "الموقع",
    AuthorEn: "Website",
    Robots: "index, follow",
    RobotsEn: "index, follow",
    "og:title": "المشاريع",
    "og:description": "مشاريعنا العقارية المتميزة",
    "og:keywords": "مشاريع, عقارية",
    "og:author": "الموقع",
    "og:robots": "index, follow",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
    "og:locale": "ar",
    "og:locale:alternate": "en",
    "og:site_name": "الموقع",
    "og:image:width": null,
    "og:image:height": null,
    "og:image:type": null,
    "og:image:alt": "المشاريع",
  },
  project: {
    TitleAr: "صفحة المشروع",
    TitleEn: "Project Page",
    DescriptionAr: "صفحة تفاصيل المشروع",
    DescriptionEn: "Project details page",
    KeywordsAr: "مشروع, تفاصيل, عقار",
    KeywordsEn: "project, details, real estate",
    Author: "الموقع",
    AuthorEn: "Website",
    Robots: "index, follow",
    RobotsEn: "index, follow",
    "og:title": "صفحة المشروع",
    "og:description": "صفحة تفاصيل المشروع",
    "og:keywords": "مشروع, تفاصيل",
    "og:author": "الموقع",
    "og:robots": "index, follow",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
    "og:locale": "ar",
    "og:locale:alternate": "en",
    "og:site_name": "الموقع",
    "og:image:width": null,
    "og:image:height": null,
    "og:image:type": null,
    "og:image:alt": "صفحة المشروع",
  },
  "about-us": {
    TitleAr: "من نحن",
    TitleEn: "About Us",
    DescriptionAr: "تعرف على شركتنا وخدماتنا المتميزة في مجال العقارات",
    DescriptionEn: "Learn about our company and our distinguished real estate services",
    KeywordsAr: "من نحن, شركة, خدمات, عقارات, معلومات",
    KeywordsEn: "about us, company, services, real estate, information",
    Author: "الموقع",
    AuthorEn: "Website",
    Robots: "index, follow",
    RobotsEn: "index, follow",
    "og:title": "من نحن",
    "og:description": "تعرف على شركتنا وخدماتنا المتميزة",
    "og:keywords": "من نحن, شركة, خدمات",
    "og:author": "الموقع",
    "og:robots": "index, follow",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
    "og:locale": "ar",
    "og:locale:alternate": "en",
    "og:site_name": "الموقع",
    "og:image:width": null,
    "og:image:height": null,
    "og:image:type": null,
    "og:image:alt": "من نحن",
  },
  "contact-us": {
    TitleAr: "اتصل بنا",
    TitleEn: "Contact Us",
    DescriptionAr: "تواصل معنا للحصول على المساعدة والاستفسارات حول العقارات",
    DescriptionEn: "Contact us for assistance and inquiries about real estate",
    KeywordsAr: "اتصل بنا, تواصل, مساعدة, خدمة العملاء, عقارات",
    KeywordsEn: "contact us, communication, help, customer service, real estate",
    Author: "الموقع",
    AuthorEn: "Website",
    Robots: "index, follow",
    RobotsEn: "index, follow",
    "og:title": "اتصل بنا",
    "og:description": "تواصل معنا للحصول على المساعدة",
    "og:keywords": "اتصل بنا, تواصل, مساعدة",
    "og:author": "الموقع",
    "og:robots": "index, follow",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
    "og:locale": "ar",
    "og:locale:alternate": "en",
    "og:site_name": "الموقع",
    "og:image:width": null,
    "og:image:height": null,
    "og:image:type": null,
    "og:image:alt": "اتصل بنا",
  },
  blog: {
    TitleAr: "صفحة المنشور",
    TitleEn: "Blog Post Page",
    DescriptionAr: "صفحة تفاصيل المنشور والمقالات",
    DescriptionEn: "Blog post details and articles page",
    KeywordsAr: "منشور, مقال, تفاصيل, مدونة",
    KeywordsEn: "blog post, article, details, blog",
    Author: "الموقع",
    AuthorEn: "Website",
    Robots: "index, follow",
    RobotsEn: "index, follow",
    "og:title": "صفحة المنشور",
    "og:description": "صفحة تفاصيل المنشور والمقالات",
    "og:keywords": "منشور, مقال, تفاصيل",
    "og:author": "الموقع",
    "og:robots": "index, follow",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
    "og:locale": "ar",
    "og:locale:alternate": "en",
    "og:site_name": "الموقع",
    "og:image:width": null,
    "og:image:height": null,
    "og:image:type": null,
    "og:image:alt": "صفحة المنشور",
  },
};

export function getDefaultSeoData(pageSlug: string): PageSeoData {
  return (
    DEFAULT_SEO_DATA[pageSlug] ||
    DEFAULT_SEO_DATA["/"] || {
      TitleAr: pageSlug.charAt(0).toUpperCase() + pageSlug.slice(1),
      TitleEn: pageSlug.charAt(0).toUpperCase() + pageSlug.slice(1),
      DescriptionAr: `صفحة ${pageSlug}`,
      DescriptionEn: `${pageSlug} page`,
      KeywordsAr: pageSlug,
      KeywordsEn: pageSlug,
      Author: "الموقع",
      AuthorEn: "Website",
      Robots: "index, follow",
      RobotsEn: "index, follow",
      "og:title": pageSlug.charAt(0).toUpperCase() + pageSlug.slice(1),
      "og:description": `صفحة ${pageSlug}`,
      "og:keywords": pageSlug,
      "og:author": "الموقع",
      "og:robots": "index, follow",
      "og:url": "",
      "og:image": "",
      "og:type": "website",
      "og:locale": "ar",
      "og:locale:alternate": "en",
      "og:site_name": "الموقع",
      "og:image:width": null,
      "og:image:height": null,
      "og:image:type": null,
      "og:image:alt": pageSlug.charAt(0).toUpperCase() + pageSlug.slice(1),
    }
  );
}
