/**
 * الصفحات الافتراضية مع بيانات SEO الخاصة بها
 * Default pages with their SEO data
 */

export interface DefaultPage {
  path: string;
  TitleAr: string;
  TitleEn: string;
  DescriptionAr: string;
  DescriptionEn: string;
  KeywordsAr: string;
  KeywordsEn: string;
  Author: string;
  AuthorEn: string;
  Robots: string;
  RobotsEn: string;
  "og:title": string;
  "og:description": string;
  "og:keywords": string;
  "og:author": string;
  "og:robots": string;
  "og:url": string;
  "og:image": string;
  "og:type": string;
  "og:locale": string;
  "og:locale:alternate": string;
  "og:site_name": string;
  "og:image:width": null;
  "og:image:height": null;
  "og:image:type": null;
  "og:image:alt": string;
}

export const DEFAULT_PAGES: DefaultPage[] = [
  {
    path: "/",
    TitleAr: "الصفحة الرئيسية",
    TitleEn: "Homepage",
    DescriptionAr: "مرحباً بكم في موقعنا - الصفحة الرئيسية",
    DescriptionEn: "Welcome to our website - Homepage",
    KeywordsAr: "الرئيسية, الموقع, الصفحة الرئيسية",
    KeywordsEn: "homepage, main, website",
    Author: "الموقع",
    AuthorEn: "Website",
    Robots: "index, follow",
    RobotsEn: "index, follow",
    "og:title": "الصفحة الرئيسية",
    "og:description": "مرحباً بكم في موقعنا",
    "og:keywords": "الرئيسية, الموقع",
    "og:author": "الموقع",
    "og:robots": "index, follow",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
    "og:locale": "ar",
    "og:locale:alternate": "en",
    "og:site_name": "الموقع",
    "og:image:width": null,
    "og:image:height": null,
    "og:image:type": null,
    "og:image:alt": "الصفحة الرئيسية",
  },
  {
    path: "/for-rent",
    TitleAr: "للإيجار",
    TitleEn: "For Rent",
    DescriptionAr: "عقارات متاحة للإيجار",
    DescriptionEn: "Properties available for rent",
    KeywordsAr: "للإيجار, عقارات, شقق, منازل",
    KeywordsEn: "for rent, properties, apartments, houses",
    Author: "الموقع",
    AuthorEn: "Website",
    Robots: "index, follow",
    RobotsEn: "index, follow",
    "og:title": "للإيجار",
    "og:description": "عقارات متاحة للإيجار",
    "og:keywords": "للإيجار, عقارات",
    "og:author": "الموقع",
    "og:robots": "index, follow",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
    "og:locale": "ar",
    "og:locale:alternate": "en",
    "og:site_name": "الموقع",
    "og:image:width": null,
    "og:image:height": null,
    "og:image:type": null,
    "og:image:alt": "للإيجار",
  },
  {
    path: "/for-sale",
    TitleAr: "للبيع",
    TitleEn: "For Sale",
    DescriptionAr: "عقارات متاحة للبيع",
    DescriptionEn: "Properties available for sale",
    KeywordsAr: "للبيع, عقارات, شقق, منازل",
    KeywordsEn: "for sale, properties, apartments, houses",
    Author: "الموقع",
    AuthorEn: "Website",
    Robots: "index, follow",
    RobotsEn: "index, follow",
    "og:title": "للبيع",
    "og:description": "عقارات متاحة للبيع",
    "og:keywords": "للبيع, عقارات",
    "og:author": "الموقع",
    "og:robots": "index, follow",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
    "og:locale": "ar",
    "og:locale:alternate": "en",
    "og:site_name": "الموقع",
    "og:image:width": null,
    "og:image:height": null,
    "og:image:type": null,
    "og:image:alt": "للبيع",
  },
  {
    path: "/projects",
    TitleAr: "المشاريع",
    TitleEn: "Projects",
    DescriptionAr: "مشاريعنا العقارية المتميزة",
    DescriptionEn: "Our distinguished real estate projects",
    KeywordsAr: "مشاريع, عقارية, تطوير, بناء",
    KeywordsEn: "projects, real estate, development, construction",
    Author: "الموقع",
    AuthorEn: "Website",
    Robots: "index, follow",
    RobotsEn: "index, follow",
    "og:title": "المشاريع",
    "og:description": "مشاريعنا العقارية المتميزة",
    "og:keywords": "مشاريع, عقارية",
    "og:author": "الموقع",
    "og:robots": "index, follow",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
    "og:locale": "ar",
    "og:locale:alternate": "en",
    "og:site_name": "الموقع",
    "og:image:width": null,
    "og:image:height": null,
    "og:image:type": null,
    "og:image:alt": "المشاريع",
  },
  {
    path: "/contact-us",
    TitleAr: "اتصل بنا",
    TitleEn: "Contact Us",
    DescriptionAr: "تواصل معنا للحصول على المساعدة",
    DescriptionEn: "Contact us for assistance",
    KeywordsAr: "اتصل بنا, تواصل, مساعدة, خدمة العملاء",
    KeywordsEn: "contact us, communication, help, customer service",
    Author: "الموقع",
    AuthorEn: "Website",
    Robots: "index, follow",
    RobotsEn: "index, follow",
    "og:title": "اتصل بنا",
    "og:description": "تواصل معنا للحصول على المساعدة",
    "og:keywords": "اتصل بنا, تواصل",
    "og:author": "الموقع",
    "og:robots": "index, follow",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
    "og:locale": "ar",
    "og:locale:alternate": "en",
    "og:site_name": "الموقع",
    "og:image:width": null,
    "og:image:height": null,
    "og:image:type": null,
    "og:image:alt": "اتصل بنا",
  },
  {
    path: "/about-us",
    TitleAr: "من نحن",
    TitleEn: "About Us",
    DescriptionAr: "تعرف على شركتنا وخدماتنا",
    DescriptionEn: "Learn about our company and services",
    KeywordsAr: "من نحن, شركة, خدمات, معلومات",
    KeywordsEn: "about us, company, services, information",
    Author: "الموقع",
    AuthorEn: "Website",
    Robots: "index, follow",
    RobotsEn: "index, follow",
    "og:title": "من نحن",
    "og:description": "تعرف على شركتنا وخدماتنا",
    "og:keywords": "من نحن, شركة",
    "og:author": "الموقع",
    "og:robots": "index, follow",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
    "og:locale": "ar",
    "og:locale:alternate": "en",
    "og:site_name": "الموقع",
    "og:image:width": null,
    "og:image:height": null,
    "og:image:type": null,
    "og:image:alt": "من نحن",
  },
  {
    path: "/about",
    TitleAr: "حول",
    TitleEn: "About",
    DescriptionAr: "معلومات حول شركتنا",
    DescriptionEn: "Information about our company",
    KeywordsAr: "حول, معلومات, شركة",
    KeywordsEn: "about, information, company",
    Author: "الموقع",
    AuthorEn: "Website",
    Robots: "index, follow",
    RobotsEn: "index, follow",
    "og:title": "حول",
    "og:description": "معلومات حول شركتنا",
    "og:keywords": "حول, معلومات",
    "og:author": "الموقع",
    "og:robots": "index, follow",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
    "og:locale": "ar",
    "og:locale:alternate": "en",
    "og:site_name": "الموقع",
    "og:image:width": null,
    "og:image:height": null,
    "og:image:type": null,
    "og:image:alt": "حول",
  },
  {
    path: "/contact",
    TitleAr: "تواصل",
    TitleEn: "Contact",
    DescriptionAr: "تواصل معنا",
    DescriptionEn: "Contact us",
    KeywordsAr: "تواصل, اتصال, مساعدة",
    KeywordsEn: "contact, communication, help",
    Author: "الموقع",
    AuthorEn: "Website",
    Robots: "index, follow",
    RobotsEn: "index, follow",
    "og:title": "تواصل",
    "og:description": "تواصل معنا",
    "og:keywords": "تواصل, اتصال",
    "og:author": "الموقع",
    "og:robots": "index, follow",
    "og:url": "",
    "og:image": "",
    "og:type": "website",
    "og:locale": "ar",
    "og:locale:alternate": "en",
    "og:site_name": "الموقع",
    "og:image:width": null,
    "og:image:height": null,
    "og:image:type": null,
    "og:image:alt": "تواصل",
  },
];
