"use client";

import React, { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import useUnifiedCustomersStore from "@/context/store/unified-customers";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { LIFECYCLE_STAGES } from "@/types/unified-customer";
import type { UnifiedCustomer, CustomerSource, Priority } from "@/types/unified-customer";
import { createIncomingAction } from "@/lib/utils/action-helpers";
import { useToast } from "@/hooks/use-toast";
import { CheckCircle2, ArrowLeft } from "lucide-react";

export default function AddCustomerPage() {
  const router = useRouter();
  const { addCustomer, addAction } = useUnifiedCustomersStore();
  const { toast } = useToast();
  
  const [formData, setFormData] = useState({
    name: "",
    phone: "",
    email: "",
    source: "manual" as CustomerSource,
    stage: "new_lead" as const,
    priority: "medium" as Priority,
    notes: "",
  });

  const handleSubmit = () => {
    // Validate required fields
    if (!formData.name || !formData.phone) {
      toast({
        title: "خطأ",
        description: "الرجاء إدخال الاسم ورقم الجوال",
        variant: "destructive",
      });
      return;
    }

    // Create new customer
    const newCustomer: UnifiedCustomer = {
      id: `cust_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      name: formData.name,
      phone: formData.phone,
      email: formData.email || undefined,
      source: formData.source,
      stage: formData.stage,
      priority: formData.priority,
      leadScore: 50,
      aiInsights: {},
      tags: [],
      stageHistory: [
        {
          id: `stage_${Date.now()}`,
          fromStage: null,
          toStage: formData.stage,
          changedBy: "System",
          changedById: "0",
          changedAt: new Date().toISOString(),
          autoGenerated: true,
        },
      ],
      preferences: {
        propertyType: [],
        preferredAreas: [],
        purpose: "buy",
        timeline: "1-3months",
      },
      properties: [],
      interactions: [],
      appointments: [],
      reminders: [],
      documents: [],
      notes: formData.notes,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    // Add customer to store
    addCustomer(newCustomer);

    // Create incoming action for the new customer
    const incomingAction = createIncomingAction(newCustomer);
    addAction(incomingAction);

    // Show success message
    toast({
      title: "تم إضافة العميل بنجاح",
      description: (
        <div className="flex items-center gap-2">
          <CheckCircle2 className="h-4 w-4 text-green-500" />
          <span>تم إنشاء إجراء وارد للعميل {formData.name}</span>
        </div>
      ),
    });

    // Redirect to customers list
    router.push("/ar/dashboard/customers-hub/list");
  };

  return (
    <div className="min-h-screen bg-white dark:bg-gray-900 p-6" dir="rtl">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="mb-6">
          <Link href="/ar/dashboard/customers-hub/list">
            <Button variant="ghost" size="sm" className="mb-4">
              <ArrowLeft className="h-4 w-4 ml-2" />
              العودة لقائمة العملاء
            </Button>
          </Link>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-2">
            إضافة عميل جديد
          </h1>
          <p className="text-gray-600 dark:text-gray-400">
            أدخل معلومات العميل الأساسية. سيتم إنشاء إجراء وارد تلقائياً.
          </p>
        </div>

        {/* Form Card */}
        <Card>
          <CardHeader>
            <CardTitle>معلومات العميل</CardTitle>
            <CardDescription>
              املأ الحقول المطلوبة لإضافة عميل جديد
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-6">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="name">الاسم *</Label>
                  <Input
                    id="name"
                    placeholder="محمد أحمد"
                    value={formData.name}
                    onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="phone">رقم الجوال *</Label>
                  <Input
                    id="phone"
                    placeholder="+966512345678"
                    dir="ltr"
                    value={formData.phone}
                    onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                  />
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="email">البريد الإلكتروني</Label>
                  <Input
                    id="email"
                    type="email"
                    placeholder="email@example.com"
                    value={formData.email}
                    onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="source">المصدر</Label>
                  <Select
                    value={formData.source}
                    onValueChange={(value) => setFormData({ ...formData, source: value as CustomerSource })}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="manual">إدخال يدوي</SelectItem>
                      <SelectItem value="inquiry">استفسار موقع</SelectItem>
                      <SelectItem value="whatsapp">واتساب</SelectItem>
                      <SelectItem value="referral">إحالة</SelectItem>
                      <SelectItem value="import">استيراد</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="stage">المرحلة</Label>
                  <Select
                    value={formData.stage}
                    onValueChange={(value) => setFormData({ ...formData, stage: value as any })}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      {LIFECYCLE_STAGES.map((stage) => (
                        <SelectItem key={stage.id} value={stage.id}>
                          {stage.nameAr}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>
                <div className="space-y-2">
                  <Label htmlFor="priority">الأولوية</Label>
                  <Select
                    value={formData.priority}
                    onValueChange={(value) => setFormData({ ...formData, priority: value as Priority })}
                  >
                    <SelectTrigger>
                      <SelectValue />
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="urgent">عاجل</SelectItem>
                      <SelectItem value="high">عالي</SelectItem>
                      <SelectItem value="medium">متوسط</SelectItem>
                      <SelectItem value="low">منخفض</SelectItem>
                    </SelectContent>
                  </Select>
                </div>
              </div>

              <div className="space-y-2">
                <Label htmlFor="notes">ملاحظات</Label>
                <Textarea
                  id="notes"
                  placeholder="أي معلومات إضافية عن العميل..."
                  rows={4}
                  value={formData.notes}
                  onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
                />
              </div>

              <div className="bg-blue-50 dark:bg-blue-950 p-4 rounded-lg border border-blue-200 dark:border-blue-800">
                <div className="flex items-start gap-2">
                  <CheckCircle2 className="h-5 w-5 text-blue-600 mt-0.5" />
                  <div>
                    <p className="text-sm font-medium text-blue-900 dark:text-blue-100">
                      سيتم إنشاء إجراء وارد تلقائياً
                    </p>
                    <p className="text-xs text-blue-700 dark:text-blue-300 mt-1">
                      سيظهر هذا العميل في مركز الإجراءات للمتابعة والتواصل
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Actions */}
        <div className="flex justify-end gap-3 mt-6">
          <Link href="/ar/dashboard/customers-hub/list">
            <Button variant="outline">
              إلغاء
            </Button>
          </Link>
          <Button onClick={handleSubmit}>
            إضافة العميل
          </Button>
        </div>
      </div>
    </div>
  );
}
