/**
 * SMS Campaigns - Mock Data
 */

import type { SMSCampaign, SMSTemplate, SMSContact, SMSStats, SMSLog } from './types';

export const mockCampaigns: SMSCampaign[] = [
  {
    id: 'c1',
    name: 'عرض نهاية الأسبوع',
    description: 'حملة ترويجية لعروض نهاية الأسبوع',
    message: 'عرض خاص! خصم 20% على جميع الشقق المتاحة في الرياض. العرض ساري حتى الأحد. اتصل الآن: 0500000000',
    status: 'sent',
    recipientCount: 1250,
    sentCount: 1250,
    deliveredCount: 1198,
    failedCount: 52,
    sentAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: 'أحمد محمد',
    tags: ['ترويج', 'عقارات'],
  },
  {
    id: 'c2',
    name: 'تذكير بموعد المعاينة',
    description: 'تذكير العملاء بمواعيد المعاينة',
    message: 'تذكير: لديك موعد معاينة غداً الساعة 3 مساءً لعقار [اسم العقار]. للاستفسار: 0500000000',
    status: 'scheduled',
    recipientCount: 45,
    sentCount: 0,
    deliveredCount: 0,
    failedCount: 0,
    scheduledAt: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    createdBy: 'سارة علي',
    tags: ['تذكير', 'معاينة'],
  },
  {
    id: 'c3',
    name: 'إطلاق مشروع جديد',
    message: 'مشروع جديد! أفخم المساكن في جدة. احجز وحدتك الآن. زوروا معرضنا أو اتصل: 0500000000',
    status: 'in-progress',
    recipientCount: 800,
    sentCount: 523,
    deliveredCount: 498,
    failedCount: 25,
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    createdBy: 'محمد خالد',
    tags: ['إطلاق', 'مشروع'],
  },
  {
    id: 'c4',
    name: 'متابعة العملاء المحتملين',
    description: 'متابعة مع العملاء الذين أبدوا اهتماماً',
    message: 'مرحباً [الاسم]، نود متابعة اهتمامك بـ[العقار]. هل لديك أي أسئلة؟ نحن هنا للمساعدة: 0500000000',
    status: 'draft',
    recipientCount: 0,
    sentCount: 0,
    deliveredCount: 0,
    failedCount: 0,
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    createdBy: 'فاطمة أحمد',
    tags: ['متابعة'],
  },
];

export const mockTemplates: SMSTemplate[] = [
  {
    id: 't1',
    name: 'ترحيب بالعميل الجديد',
    content: 'مرحباً [name]! نشكرك على اهتمامك بخدماتنا العقارية. نحن هنا لمساعدتك في إيجاد منزل أحلامك.',
    category: 'transactional',
    variables: ['name'],
    isActive: true,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 't2',
    name: 'عرض عقار جديد',
    content: 'عقار جديد! [property] متاح الآن بسعر [price] ريال. [bedrooms] غرف نوم. للتفاصيل: [link]',
    category: 'promotional',
    variables: ['property', 'price', 'bedrooms', 'link'],
    isActive: true,
    createdAt: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 't3',
    name: 'تذكير بالموعد',
    content: 'تذكير: لديك موعد [type] يوم [date] الساعة [time]. الموقع: [location]. للتأكيد: [phone]',
    category: 'reminder',
    variables: ['type', 'date', 'time', 'location', 'phone'],
    isActive: true,
    createdAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 't4',
    name: 'طلب تقييم',
    content: 'مرحباً [name]، نأمل أن تكون راضياً عن خدماتنا. هل يمكنك تقييم تجربتك؟ [link]',
    category: 'follow-up',
    variables: ['name', 'link'],
    isActive: true,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const mockContacts: SMSContact[] = [
  { id: '1', name: 'أحمد محمد', phone: '+966501234567', tags: ['مهتم', 'رياض'], isSubscribed: true },
  { id: '2', name: 'فاطمة علي', phone: '+966507654321', tags: ['عميل'], isSubscribed: true },
  { id: '3', name: 'خالد عبدالله', phone: '+966509876543', tags: ['محتمل'], isSubscribed: true },
  { id: '4', name: 'نورة سعد', phone: '+966503456789', tags: ['جدة', 'مهتم'], isSubscribed: false },
  { id: '5', name: 'محمد خالد', phone: '+966502345678', tags: ['عميل', 'فيلا'], isSubscribed: true },
];

export const mockStats: SMSStats = {
  totalCampaigns: 24,
  totalSent: 15780,
  totalDelivered: 14952,
  totalFailed: 828,
  deliveryRate: 94.8,
  thisMonthSent: 3420,
};

export const mockLogs: SMSLog[] = [
  {
    id: 'l1',
    campaignId: 'c1',
    campaignName: 'عرض نهاية الأسبوع',
    contactId: '1',
    contactName: 'أحمد محمد',
    phone: '+966501234567',
    message: 'عرض خاص! خصم 20% على جميع الشقق...',
    status: 'delivered',
    sentAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    deliveredAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 30000).toISOString(),
  },
  {
    id: 'l2',
    campaignId: 'c1',
    campaignName: 'عرض نهاية الأسبوع',
    contactId: '2',
    contactName: 'فاطمة علي',
    phone: '+966507654321',
    message: 'عرض خاص! خصم 20% على جميع الشقق...',
    status: 'delivered',
    sentAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    deliveredAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000 + 25000).toISOString(),
  },
  {
    id: 'l3',
    campaignId: 'c3',
    campaignName: 'إطلاق مشروع جديد',
    contactId: '3',
    contactName: 'خالد عبدالله',
    phone: '+966509876543',
    message: 'مشروع جديد! أفخم المساكن في جدة...',
    status: 'sent',
    sentAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
  },
  {
    id: 'l4',
    campaignId: 'c1',
    campaignName: 'عرض نهاية الأسبوع',
    contactId: '4',
    contactName: 'نورة سعد',
    phone: '+966503456789',
    message: 'عرض خاص! خصم 20% على جميع الشقق...',
    status: 'failed',
    sentAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    errorMessage: 'رقم غير صالح',
  },
];
