import type {
  Conversation,
  Message,
  MessageTemplate,
  AutomationRule,
  AIResponderConfig,
  WhatsAppNumber,
  AutomationStats,
  AIStats,
} from "./types";

// Mock WhatsApp Numbers
export const mockWhatsAppNumbers: WhatsAppNumber[] = [
  {
    id: 1,
    phoneNumber: "+966501234567",
    name: "الرقم الرئيسي",
    status: "active",
    employee: {
      id: 1,
      name: "أحمد محمد",
      email: "ahmed@example.com",
    },
  },
  {
    id: 2,
    phoneNumber: "+966559876543",
    name: "خدمة العملاء",
    status: "active",
    employee: {
      id: 2,
      name: "فاطمة أحمد",
      email: "fatima@example.com",
    },
  },
  {
    id: 3,
    phoneNumber: "+966551112222",
    name: "المبيعات",
    status: "active",
  },
];

// Mock Conversations
export const mockConversations: Conversation[] = [
  {
    id: "conv-1",
    customerId: "cust-1",
    customerName: "محمد العتيبي",
    customerPhone: "+966501111111",
    customerAvatar: undefined,
    whatsappNumberId: 1,
    lastMessage: "هل يمكن حجز موعد معاينة للفيلا؟",
    lastMessageTime: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
    unreadCount: 2,
    status: "active",
    isStarred: true,
    propertyInterests: [
      {
        id: "prop-1",
        propertyName: "فيلا فاخرة في الرياض",
        propertyType: "فيلا",
        location: "الرياض - حي النرجس",
        price: 2500000,
        status: "viewing_scheduled",
      },
    ],
    assignedAgent: {
      id: "1",
      name: "أحمد محمد",
    },
  },
  {
    id: "conv-2",
    customerId: "cust-2",
    customerName: "سارة الأحمد",
    customerPhone: "+966502222222",
    whatsappNumberId: 1,
    lastMessage: "شكراً لكم، سأراجع العروض وأرد عليكم",
    lastMessageTime: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
    status: "pending",
    isStarred: false,
    propertyInterests: [
      {
        id: "prop-2",
        propertyName: "شقة حديثة",
        propertyType: "شقة",
        location: "جدة - حي الفيحاء",
        price: 800000,
        status: "interested",
      },
    ],
  },
  {
    id: "conv-3",
    customerId: "cust-3",
    customerName: "خالد السالم",
    customerPhone: "+966503333333",
    whatsappNumberId: 2,
    lastMessage: "ما هي شروط التمويل؟",
    lastMessageTime: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    unreadCount: 1,
    status: "active",
    isStarred: false,
    propertyInterests: [],
  },
  {
    id: "conv-4",
    customerId: "cust-4",
    customerName: "نورة الدوسري",
    customerPhone: "+966504444444",
    whatsappNumberId: 1,
    lastMessage: "تم إتمام الصفقة، شكراً لجهودكم",
    lastMessageTime: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    unreadCount: 0,
    status: "resolved",
    isStarred: false,
    propertyInterests: [
      {
        id: "prop-3",
        propertyName: "أرض تجارية",
        propertyType: "أرض",
        location: "الدمام",
        price: 1500000,
        status: "not_interested",
      },
    ],
  },
  {
    id: "conv-5",
    customerId: "cust-5",
    customerName: "عبدالله المطيري",
    customerPhone: "+966505555555",
    whatsappNumberId: 2,
    lastMessage: "مساء الخير، أود الاستفسار عن عقارات للإيجار",
    lastMessageTime: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    unreadCount: 1,
    status: "active",
    isStarred: false,
    propertyInterests: [],
  },
];

// Mock Messages for a conversation
export const mockMessages: Record<string, Message[]> = {
  "conv-1": [
    {
      id: "msg-1",
      conversationId: "conv-1",
      content: "السلام عليكم، أنا مهتم بفيلا في حي النرجس",
      sender: "customer",
      timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
      status: "read",
    },
    {
      id: "msg-2",
      conversationId: "conv-1",
      content: "وعليكم السلام، أهلاً وسهلاً بك. لدينا عدة خيارات رائعة في حي النرجس. هل لديك مساحة أو ميزانية محددة؟",
      sender: "agent",
      senderName: "أحمد محمد",
      timestamp: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
      status: "read",
    },
    {
      id: "msg-3",
      conversationId: "conv-1",
      content: "أبحث عن فيلا بمساحة 400-500 متر، والميزانية حوالي 2-2.5 مليون",
      sender: "customer",
      timestamp: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
      status: "read",
    },
    {
      id: "msg-4",
      conversationId: "conv-1",
      content: "ممتاز! لدي فيلا تناسب متطلباتك تماماً:\n\n🏠 فيلا فاخرة في حي النرجس\n📏 المساحة: 450 م²\n💰 السعر: 2,500,000 ريال\n🛏️ 5 غرف نوم\n🚿 6 حمامات\n🚗 موقف سيارتين\n\nهل تود معاينة العقار؟",
      sender: "agent",
      senderName: "أحمد محمد",
      timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
      status: "read",
    },
    {
      id: "msg-5",
      conversationId: "conv-1",
      content: "نعم، العقار يبدو مناسب. هل يمكن حجز موعد معاينة للفيلا؟",
      sender: "customer",
      timestamp: new Date(Date.now() - 5 * 60 * 1000).toISOString(),
      status: "delivered",
    },
  ],
  "conv-2": [
    {
      id: "msg-6",
      conversationId: "conv-2",
      content: "مرحباً، هل لديكم شقق للبيع في جدة؟",
      sender: "customer",
      timestamp: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
      status: "read",
    },
    {
      id: "msg-7",
      conversationId: "conv-2",
      content: "أهلاً بك! نعم لدينا عدة شقق متاحة في جدة. ما هي المنطقة المفضلة لديك؟",
      sender: "agent",
      senderName: "أحمد محمد",
      timestamp: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
      status: "read",
    },
    {
      id: "msg-8",
      conversationId: "conv-2",
      content: "شكراً لكم، سأراجع العروض وأرد عليكم",
      sender: "customer",
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
      status: "read",
    },
  ],
  "conv-3": [
    {
      id: "msg-9",
      conversationId: "conv-3",
      content: "ما هي شروط التمويل؟",
      sender: "customer",
      timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      status: "read",
    },
  ],
};

// Mock Message Templates
export const mockMessageTemplates: MessageTemplate[] = [
  {
    id: "template-1",
    name: "تحية وترحيب",
    content: "مرحباً {customer_name}،\n\nنشكرك على اهتمامك بخدماتنا العقارية. نحن هنا لمساعدتك في إيجاد العقار المثالي.\n\nفريق {company_name}",
    category: "general",
    variables: ["customer_name", "company_name"],
  },
  {
    id: "template-2",
    name: "عقارات مطابقة",
    content: "السلام عليكم {customer_name}،\n\nوجدنا {property_count} عقار يطابق تفضيلاتك:\n\n📍 الموقع: {location}\n💰 السعر: {price} ريال\n🏠 النوع: {property_type}\n\nهل ترغب في معاينة هذه العقارات؟",
    category: "properties",
    variables: ["customer_name", "property_count", "location", "price", "property_type"],
  },
  {
    id: "template-3",
    name: "تذكير بالموعد",
    content: "مرحباً {customer_name}،\n\n🗓️ تذكير بموعدك:\n📅 التاريخ: {date}\n⏰ الوقت: {time}\n📍 المكان: {location}\n\nنتطلع لرؤيتك!",
    category: "appointments",
    variables: ["customer_name", "date", "time", "location"],
  },
  {
    id: "template-4",
    name: "متابعة دورية",
    content: "السلام عليكم {customer_name}،\n\nكيف حالك؟ نود متابعة بحثك عن العقار المناسب.\n\n✨ لدينا عروض جديدة قد تهمك\n📞 هل ترغب في حجز موعد؟\n\nنحن هنا لخدمتك.",
    category: "follow_up",
    variables: ["customer_name"],
  },
  {
    id: "template-5",
    name: "لا يوجد رد - 24 ساعة",
    content: "مرحباً {customer_name}،\n\nنأمل أن تكون بخير. لاحظنا عدم تلقينا رداً منك.\n\nهل ما زلت مهتماً بـ {property_name}؟ نحن هنا لمساعدتك في أي استفسارات.\n\nفريق {company_name}",
    category: "follow_up",
    variables: ["customer_name", "property_name", "company_name"],
  },
];

// Mock Automation Rules
export const mockAutomationRules: AutomationRule[] = [
  {
    id: "rule-1",
    name: "رسالة ترحيب للعملاء الجدد",
    description: "إرسال رسالة ترحيب تلقائية عند استلام استفسار جديد",
    trigger: "new_inquiry",
    delayMinutes: 0,
    templateId: "template-1",
    template: mockMessageTemplates[0],
    isActive: true,
    createdAt: "2024-01-15",
    lastTriggered: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    triggeredCount: 145,
  },
  {
    id: "rule-2",
    name: "متابعة بعد 24 ساعة",
    description: "متابعة العميل إذا لم يرد خلال 24 ساعة",
    trigger: "no_response_24h",
    delayMinutes: 1440,
    templateId: "template-5",
    template: mockMessageTemplates[4],
    isActive: true,
    createdAt: "2024-01-10",
    lastTriggered: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    triggeredCount: 67,
  },
  {
    id: "rule-3",
    name: "تذكير بالموعد",
    description: "تذكير العميل بموعد المعاينة قبل 24 ساعة",
    trigger: "appointment_reminder",
    delayMinutes: 1440,
    templateId: "template-3",
    template: mockMessageTemplates[2],
    isActive: true,
    createdAt: "2024-01-05",
    lastTriggered: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
    triggeredCount: 234,
  },
  {
    id: "rule-4",
    name: "إشعار بعقارات مطابقة",
    description: "إرسال رسالة عند توفر عقار يطابق تفضيلات العميل",
    trigger: "property_match",
    delayMinutes: 0,
    templateId: "template-2",
    template: mockMessageTemplates[1],
    isActive: true,
    createdAt: "2024-01-20",
    lastTriggered: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    triggeredCount: 89,
  },
  {
    id: "rule-5",
    name: "متابعة بعد 48 ساعة",
    description: "متابعة ثانية إذا لم يرد العميل خلال 48 ساعة",
    trigger: "no_response_48h",
    delayMinutes: 2880,
    templateId: "template-4",
    template: mockMessageTemplates[3],
    isActive: false,
    createdAt: "2024-01-08",
    triggeredCount: 23,
  },
];

// Mock AI Responder Configs
export const mockAIResponderConfigs: AIResponderConfig[] = [
  {
    id: "ai-config-1",
    whatsappNumberId: 1,
    enabled: true,
    businessHoursOnly: true,
    businessHours: {
      start: "09:00",
      end: "18:00",
      timezone: "Asia/Riyadh",
    },
    scenarios: {
      initialGreeting: true,
      faqResponses: true,
      propertyInquiryResponse: true,
      appointmentBooking: false,
      generalQuestions: true,
    },
    tone: "friendly",
    language: "both",
    customInstructions: "استخدم لهجة ودية ومهنية. ركز على خدمة العملاء الممتازة.",
    fallbackToHuman: true,
    fallbackDelay: 5,
  },
  {
    id: "ai-config-2",
    whatsappNumberId: 2,
    enabled: true,
    businessHoursOnly: false,
    scenarios: {
      initialGreeting: true,
      faqResponses: true,
      propertyInquiryResponse: true,
      appointmentBooking: true,
      generalQuestions: true,
    },
    tone: "professional",
    language: "ar",
    fallbackToHuman: true,
    fallbackDelay: 10,
  },
  {
    id: "ai-config-3",
    whatsappNumberId: 3,
    enabled: false,
    businessHoursOnly: false,
    scenarios: {
      initialGreeting: false,
      faqResponses: false,
      propertyInquiryResponse: false,
      appointmentBooking: false,
      generalQuestions: false,
    },
    tone: "formal",
    language: "ar",
    fallbackToHuman: true,
    fallbackDelay: 5,
  },
];

// Mock Stats
export const mockAutomationStats: AutomationStats = {
  totalRules: 5,
  activeRules: 4,
  messagesSent24h: 87,
  successRate: 94.5,
};

export const mockAIStats: AIStats = {
  totalResponses24h: 156,
  avgResponseTime: 2.3,
  satisfactionRate: 91.2,
  handoffRate: 8.5,
};
