"use client";

import React, { useState } from "react";
import useUnifiedCustomersStore from "@/context/store/unified-customers";
import {
  CustomDialog,
  CustomDialogContent,
  CustomDialogDescription,
  CustomDialogHeader,
  CustomDialogTitle,
  CustomDialogClose,
} from "@/components/customComponents/CustomDialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { LIFECYCLE_STAGES } from "@/types/unified-customer";
import type { UnifiedCustomer, CustomerSource, Priority } from "@/types/unified-customer";
import { createIncomingAction } from "@/lib/utils/action-helpers";
import { useToast } from "@/hooks/use-toast";
import { CheckCircle2 } from "lucide-react";

export function AddCustomerDialog() {
  const { showAddCustomerDialog, setShowAddCustomerDialog, addCustomer, addAction } = useUnifiedCustomersStore();
  const { toast } = useToast();
  
  const [formData, setFormData] = useState({
    name: "",
    phone: "",
    email: "",
    source: "manual" as CustomerSource,
    stage: "new_lead" as const,
    priority: "medium" as Priority,
    notes: "",
  });

  const handleSubmit = () => {
    // Validate required fields
    if (!formData.name || !formData.phone) {
      toast({
        title: "خطأ",
        description: "الرجاء إدخال الاسم ورقم الجوال",
        variant: "destructive",
      });
      return;
    }

    // Create new customer
    const newCustomer: UnifiedCustomer = {
      id: `cust_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`,
      name: formData.name,
      phone: formData.phone,
      email: formData.email || undefined,
      source: formData.source,
      stage: formData.stage,
      priority: formData.priority,
      leadScore: 50,
      aiInsights: {},
      tags: [],
      stageHistory: [
        {
          id: `stage_${Date.now()}`,
          fromStage: null,
          toStage: formData.stage,
          changedBy: "System",
          changedById: "0",
          changedAt: new Date().toISOString(),
          autoGenerated: true,
        },
      ],
      preferences: {
        propertyType: [],
        preferredAreas: [],
        purpose: "buy",
        timeline: "1-3months",
      },
      properties: [],
      interactions: [],
      appointments: [],
      reminders: [],
      documents: [],
      notes: formData.notes,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    // Add customer to store
    addCustomer(newCustomer);

    // Create incoming action for the new customer
    const incomingAction = createIncomingAction(newCustomer);
    addAction(incomingAction);

    // Show success message
    toast({
      title: "تم إضافة العميل بنجاح",
      description: (
        <div className="flex items-center gap-2">
          <CheckCircle2 className="h-4 w-4 text-green-500" />
          <span>تم إنشاء إجراء وارد للعميل {formData.name}</span>
        </div>
      ),
    });

    // Reset form and close dialog
    setFormData({
      name: "",
      phone: "",
      email: "",
      source: "manual",
      stage: "new_lead",
      priority: "medium",
      notes: "",
    });
    setShowAddCustomerDialog(false);
  };

  return (
    <CustomDialog open={showAddCustomerDialog} onOpenChange={setShowAddCustomerDialog} maxWidth="max-w-2xl">
      <CustomDialogContent className="dir-rtl">
        <CustomDialogClose onClose={() => setShowAddCustomerDialog(false)} />
        <CustomDialogHeader>
          <CustomDialogTitle>إضافة عميل جديد</CustomDialogTitle>
          <CustomDialogDescription>
            أدخل معلومات العميل الأساسية. سيتم إنشاء إجراء وارد تلقائياً.
          </CustomDialogDescription>
        </CustomDialogHeader>

        <div className="space-y-4 py-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="name">الاسم *</Label>
              <Input
                id="name"
                placeholder="محمد أحمد"
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="phone">رقم الجوال *</Label>
              <Input
                id="phone"
                placeholder="+966512345678"
                dir="ltr"
                value={formData.phone}
                onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
              />
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="email">البريد الإلكتروني</Label>
              <Input
                id="email"
                type="email"
                placeholder="email@example.com"
                value={formData.email}
                onChange={(e) => setFormData({ ...formData, email: e.target.value })}
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="source">المصدر</Label>
              <Select
                value={formData.source}
                onValueChange={(value) => setFormData({ ...formData, source: value as CustomerSource })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="manual">إدخال يدوي</SelectItem>
                  <SelectItem value="inquiry">استفسار موقع</SelectItem>
                  <SelectItem value="whatsapp">واتساب</SelectItem>
                  <SelectItem value="referral">إحالة</SelectItem>
                  <SelectItem value="import">استيراد</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="stage">المرحلة</Label>
              <Select
                value={formData.stage}
                onValueChange={(value) => setFormData({ ...formData, stage: value as any })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {LIFECYCLE_STAGES.map((stage) => (
                    <SelectItem key={stage.id} value={stage.id}>
                      {stage.nameAr}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <Label htmlFor="priority">الأولوية</Label>
              <Select
                value={formData.priority}
                onValueChange={(value) => setFormData({ ...formData, priority: value as Priority })}
              >
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="urgent">عاجل</SelectItem>
                  <SelectItem value="high">عالي</SelectItem>
                  <SelectItem value="medium">متوسط</SelectItem>
                  <SelectItem value="low">منخفض</SelectItem>
                </SelectContent>
              </Select>
            </div>
          </div>

          <div className="space-y-2">
            <Label htmlFor="notes">ملاحظات</Label>
            <Textarea
              id="notes"
              placeholder="أي معلومات إضافية عن العميل..."
              rows={3}
              value={formData.notes}
              onChange={(e) => setFormData({ ...formData, notes: e.target.value })}
            />
          </div>

          <div className="bg-blue-50 dark:bg-blue-950 p-3 rounded-lg border border-blue-200 dark:border-blue-800">
            <div className="flex items-start gap-2">
              <CheckCircle2 className="h-5 w-5 text-blue-600 mt-0.5" />
              <div>
                <p className="text-sm font-medium text-blue-900 dark:text-blue-100">
                  سيتم إنشاء إجراء وارد تلقائياً
                </p>
                <p className="text-xs text-blue-700 dark:text-blue-300 mt-1">
                  سيظهر هذا العميل في مركز الإجراءات للمتابعة والتواصل
                </p>
              </div>
            </div>
          </div>
        </div>

        <div className="flex justify-end gap-2 px-4 sm:px-6 py-3 sm:py-4 border-t border-gray-200">
          <Button
            variant="outline"
            onClick={() => setShowAddCustomerDialog(false)}
          >
            إلغاء
          </Button>
          <Button onClick={handleSubmit}>
            إضافة العميل
          </Button>
        </div>
      </CustomDialogContent>
    </CustomDialog>
  );
}
